export const products = [
  {
    id: 23423,
    name: "BOSCH ABS 2-LED-TESTER KDAS 0003 FOR 2nd GENERATION ABS ANTILOCK BRAKING SYSTEM",
    stock_quantity: 8,
    description:
      " A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is applicable). Packaging should be the same as what is found in a retail store, unless the item was packaged by the manufacturer in non-retail packaging, such as an unprinted box or plastic bag. See the seller's listing for full details. ",
    price: 1200,
    images: [
      "/bosch 1.webp",
      "/bosch 2.webp",
      "/bosch 3.webp",
      "/bosch 4.webp",
      "/bosch 5.webp",
    ],
    category: "Industrial Automation & Motion Controls",
    condition: "New",
    model: "ABS 2-LED-TESTER KDAS 0003",
    brand: "Bosch",
    country_of_origin: "Germany",
    discountPercentage: 25,
    discountStartDate: "2025-12-3",
    discountEndDate: "2025-12-31",
    free_shipping: true,
    meta_description: "",
    meta_title: "",
    weight: "",
    dimension: "",
    SKU: "o834hi87fsoih2",
    is_featured: true,
    is_active: true,
    type: "",
    mpn: "",
    slug: "",
  },
  {
    id: 435,
    name: "CAMERON CD-20A CLIF MOCK CONTROLLER",
    stock_quantity: 3,
    description:
      " An item in excellent, new condition with no functional defects. The item may be missing original packaging and may have been used for testing or demo purposes. The item includes accessories found with the original product and may include a warranty. See the seller's listing for full details and description.",
    price: 1200,
    images: ["/cm1.webp", "/cm2.webp", "/cm3.webp", "/cm4.webp", "/cm5.webp"],
    category: "Industrial Automation & Motion Controls",
    condition: "New - Open box",
    model: "CD-20A",
    brand: "CAMERON",
    country_of_origin: "United States",
    discountPercentage: 0,
    discountStartDate: "2023-01-01",
    discountEndDate: "2023-12-31",
    free_shipping: true,
    meta_description: "",
    meta_title: "",
    weight: "",
    dimension: "",
    SKU: "23hiuhia2iubgf",
    is_featured: true,
    is_active: true,
    type: "",
    mpn: "",
    slug: "",
  },
  {
    id: 634,
    name: "FEDERAL SIGNAL G-STR-024-D-X-15J VISUAL STROBE GLOBAL SERIES",
    stock_quantity: 3,
    description:
      "An item in excellent, new condition with no functional defects. The item may be missing original packaging and may have been used for testing or demo purposes. The item includes accessories found with the original product and may include a warranty. See the seller's listing for full details and description.",
    price: 599,
    images: ["/fs1.webp", "/fs2.webp", "/fs3.webp", "/fs4.webp", "/fs5.webp"],
    category: "Industrial Automation & Motion Controls",
    condition: "New - Open box",
    model: "G-STR-024-D-X-15J",
    brand: "FEDERAL SIGNAL",
    country_of_origin: "United States",
    discountPercentage: 0,
    discountStartDate: "2023-01-01",
    discountEndDate: "2023-12-31",
    free_shipping: true,
    meta_description: "",
    meta_title: "",
    weight: "",
    dimension: "",
    SKU: "23hiuhia2iubgf",
    is_featured: true,
    is_active: true,
    type: "",
    mpn: "",
    slug: "",
  },
  {
    id: 454,
    name: "GE ElectroLogIXS 251464-000 CHASSIS 4 SLOT BACKPLANE 227626-000 , 062425-000",
    stock_quantity: 6,
    description:
      "An item in excellent, new condition with no functional defects. The item may be missing original packaging and may have been used for testing or demo purposes. The item includes accessories found with the original product and may include a warranty. See the seller's listing for full details and description",
    price: 3499,
    images: ["/ge1.webp", "/ge2.webp", "/ge 3.webp", "/ge4.webp", "/ge5.webp"],
    category: "Industrial Automation & Motion Controls",
    condition: "New - Open box",
    model: "GE ElectroLogIXS 251464-000",
    brand: "GE",
    country_of_origin: "",
    discountPercentage: 0,
    discountStartDate: "",
    discountEndDate: "",
    free_shipping: true,
    meta_description: "",
    meta_title: "",
    weight: "",
    dimension: "",
    SKU: "23hiuhia2iubgf",
    is_featured: true,
    is_active: true,
    type: "",
    mpn: "",
    slug: "",
  },
  {
    id: 53,
    name: "SCHISCHEK InMax-5.10-SF 1/4 TURN ACTUATOR 5/10 Nm",
    stock_quantity: 3,
    description:
      "A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is applicable). Packaging should be the same as what is found in a retail store, unless the item was packaged by the manufacturer in non-retail packaging, such as an unprinted box or plastic bag. See the seller's listing for full details.",
    price: 1099,
    images: ["/sc 1.webp", "/sc2.webp", "/sc3.webp", "/sc4.webp", "/sc5.webp"],
    category: "Industrial Automation & Motion Controls",
    condition: "New",
    model: "SCHISCHEK InMax-5.10-SF",
    brand: "SCHISCHEK",
    country_of_origin: "Germany",
    discountPercentage: 0,
    discountStartDate: "",
    discountEndDate: "",
    free_shipping: true,
    meta_description: "",
    meta_title: "",
    weight: "",
    dimension: "",
    SKU: "23hiuhia2iubgf",
    is_featured: true,
    is_active: true,
    type: "",
    mpn: "",
    slug: "",
  },
  {
    id: 898,
    name: "AIR N MICRO MANO METER Model MP6KSR",
    stock_quantity: 3,
    description:
      "An item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended. This item may be a floor model or store return that has been used. See the seller’s listing for full details and description of any imperfections",
    price: 299,
    images: [
      "/s-l1600 (8).webp",
      "/s-l1600 (10).webp",
      "/air in micro mano 1.webp",
      "/air micro 4.webp",
      "/s-l1600 (7).webp",
    ],
    category: "Consumer Electronics",
    condition: "Used",
    model: "",
    brand: "air n",
    country_of_origin: "",
    discountPercentage: 0,
    discountStartDate: "",
    discountEndDate: "",
    free_shipping: true,
    meta_description: "",
    meta_title: "",
    weight: "",
    dimension: "",
    SKU: "23hiuhia2iubgf",
    is_featured: true,
    is_active: true,
    type: "",
    mpn: "",
    slug: "",
  },
  {
    id: 548,
    name: "COBHAM SAILOR B3504 ATEX – Rechargeable Secondary Battery 7.2V Li-Ion S-403504A",
    stock_quantity: 6,
    description:
      "An item in excellent, new condition with no wear. The item may be missing the original packaging or protective wrapping, or may be in the original packaging but not sealed. The item includes original accessories. The item may be a factory second. See the seller's listing for full details and description.",
    price: 375,
    images: [
      "/s-l1600.webp",
      "/s-l1600 (2).webp",
      "/s-l1600 (3).webp",
      "/s-l1600 (4).webp",
      "/s-l1600 (5).webp",
    ],
    category: "Consumer Electronics",
    condition: "Open box",
    model: "S-403504A",
    brand: "COBHAM",
    country_of_origin: "Denmark",
    discountPercentage: 0,
    discountStartDate: "",
    discountEndDate: "",
    free_shipping: true,
    meta_description: "",
    meta_title: "",
    weight: "",
    dimension: "",
    SKU: "23hiuhia2iubgf",
    is_featured: true,
    is_active: true,
    type: "",
    mpn: "",
    slug: "",
  },
  {
    id: 584,
    name: "EMERSON DELTAV KJ2221X1-EA1 SISNET REPEATER CARRIER 12P3241X022 Rev :E",
    stock_quantity: 4,
    description:
      "An item in excellent, new condition with no wear. The item may be missing the original packaging or protective wrapping, or may be in the original packaging but not sealed. The item includes original accessories. The item may be a factory second. See the seller's listing for full details and description.",
    price: 429,
    images: [
      "/emer1.webp",
      "/emer2.webp",
      "/emer3.webp",
      "/emer4.webp",
      "/emer5.webp",
    ],
    category: "Consumer Electronics",
    condition: "Open box",
    model: "S-403504A",
    brand: "Emerson",
    country_of_origin: "",
    discountPercentage: 0,
    discountStartDate: "",
    discountEndDate: "",
    free_shipping: true,
    meta_description: "",
    meta_title: "",
    weight: "",
    dimension: "",
    SKU: "23hiuhia2iubgf",
    is_featured: true,
    is_active: true,
    type: "",
    mpn: "",
    slug: "",
  },
  {
    id: 284,
    name: "New Factory Sealed Allen-Bradley 1756-IF8 /A ControlLogix Point A/I Module",
    stock_quantity: 4,
    description:
      "An item in excellent, new condition with no wear. The item may be missing the original packaging or protective wrapping, or may be in the original packaging but not sealed. The item includes original accessories. The item may be a factory second. See the seller's listing for full details and description.",
    price: 429,
    images: [
      "/new factory 1.webp",
      "/new factory 2.webp",
      "/new factory 3.webp",
      "/new factory 4.webp",
      "/new factory 5.webp",
    ],
    category: "Consumer Electronics",
    condition: "New",
    model: "1756-IF8",
    brand: "Allen-Bradley",
    country_of_origin: "",
    discountPercentage: 0,
    discountStartDate: "",
    discountEndDate: "",
    free_shipping: true,
    meta_description: "",
    meta_title: "",
    weight: "",
    dimension: "",
    SKU: "23hiuhia2iubgf",
    is_featured: true,
    is_active: true,
    type: "",
    mpn: "",
    slug: "",
  },
  {
    id: 193,
    name: "WARTSILA DIESEL VAISALA QLI50 SW 1.04",
    stock_quantity: 6,
    description:
      "An item in excellent, new condition with no wear. The item may be missing the original packaging or protective wrapping, or may be in the original packaging but not sealed. The item includes original accessories. The item may be a factory second. See the seller's listing for full details and description.",
    price: 1999,
    images: [
      "/WARTSILA DIESEL 1.webp",
      "/WARTSILA DIESEL 2.webp",
      "/WARTSILA DIESEL 3.webp",
      "/WARTSILA DIESEL VAISALA 4.webp",
      "/WARTSILA DIESEL 5.webp",
    ],
    category: "Consumer Electronics",
    condition: "Open box",
    model: "QLI50 SW 1.04",
    brand: "WARTSILA DIESEL",
    country_of_origin: "",
    discountPercentage: 0,
    discountStartDate: "",
    discountEndDate: "",
    free_shipping: true,
    meta_description: "",
    meta_title: "",
    weight: "",
    dimension: "",
    SKU: "23hiuhia2iubgf",
    is_featured: true,
    is_active: true,
    type: "",
    mpn: "",
    slug: "",
  },
  {
    id: 1934,
    name: "AUTRONICA BHH-500/S HIGH SENSE SMOKE DETECTOR 116-BHH-500/S *NEW*",
    stock_quantity: 16,
    description:
      "An item in excellent, new condition with no wear. The item may be missing the original packaging or protective wrapping, or may be in the original packaging but not sealed. The item includes original accessories. The item may be a factory second. See the seller's listing for full details and description.",
    price: 299,
    images: [
      "/auto 1.webp",
      "/auto 2.webp",
      "/auto 3.webp",
      "/auto 4.webp",
      "/auto 5.webp",
    ],
    category: "Home & Garden",
    condition: "New",
    model: "BHH-500/S",
    brand: "AUTRONICA FIRE AND SECURITY",
    country_of_origin: "Norway",
    discountPercentage: 0,
    discountStartDate: "",
    discountEndDate: "",
    free_shipping: false,
    meta_description: "",
    meta_title: "",
    weight: "",
    dimension: "",
    SKU: "23hiuhia2iubgf",
    is_featured: true,
    is_active: true,
    type: "",
    mpn: "",
    slug: "",
  },
  {
    id: 2947,
    name: "CABAC HN2 COPPER LUG HAND CRIMPER 1.5MM-10MM2",
    stock_quantity: 12,
    description:
      "An item in excellent, new condition with no wear. The item may be missing the original packaging or protective wrapping, or may be in the original packaging but not sealed. The item includes original accessories. The item may be a factory second. See the seller's listing for full details and description.",
    price: 299,
    images: ["/ca1.webp", "/ca2.webp", "/ca3.webp", "/ca4.webp", "/ca5.webp"],
    category: "Home & Garden",
    condition: "New",
    model: "",
    brand: "CABAC",
    country_of_origin: "",
    discountPercentage: 42,
    discountStartDate: "",
    discountEndDate: "",
    free_shipping: false,
    meta_description: "",
    meta_title: "",
    weight: "",
    dimension: "",
    SKU: "23hiuhia2iubgf",
    is_featured: true,
    is_active: true,
    type: "",
    mpn: "",
    slug: "",
  },
  {
    id: 58903,
    name: "CLECO 962085PT LiveWire 26/44V HC Multicharger – Li-Ion Battery Charger",
    stock_quantity: 12,
    description:
      "An item in excellent, new condition with no wear. The item may be missing the original packaging or protective wrapping, or may be in the original packaging but not sealed. The item includes original accessories. The item may be a factory second. See the seller's listing for full details and description.",
    price: 299,
    images: ["/cl1.webp", "/cl2.webp", "/cl3.webp", "/cl4.webp", "/cl5.webp"],
    category: "Home & Garden",
    condition: "New",
    model: "LiveWire 26/44V HC Multicharger",
    brand: "CLECO",
    country_of_origin: "Germany",
    discountPercentage: 0,
    discountStartDate: "",
    discountEndDate: "",
    free_shipping: false,
    meta_description: "",
    meta_title: "",
    weight: "",
    dimension: "",
    SKU: "23hiuhia2iubgf",
    is_featured: true,
    is_active: true,
    type: "",
    mpn: "",
    slug: "",
  },
  {
    id: 29820,
    name: "VISIONX 29-MRXP1260 RIPPER WORKLIGHT 12 LED 60DEG",
    stock_quantity: 12,
    description:
      "An item in excellent, new condition with no wear. The item may be missing the original packaging or protective wrapping, or may be in the original packaging but not sealed. The item includes original accessories. The item may be a factory second. See the seller's listing for full details and description.",
    price: 899,
    images: [
      "/vision 1.webp",
      "/vision 2.webp",
      "/vision 3.webp",
      "/vision 4.webp",
      "/vision 5.webp",
    ],
    category: "Home & Garden",
    condition: "New",
    model: "",
    brand: "VISIONX",
    country_of_origin: "Australia",
    discountPercentage: 25,
    discountStartDate: "2025-12-3",
    discountEndDate: "2025-12-31",
    free_shipping: false,
    meta_description: "",
    meta_title: "",
    weight: "",
    dimension: "",
    SKU: "23hiuhia2iubgf",
    is_featured: true,
    is_active: true,
    type: "",
    mpn: "",
    slug: "",
  },
];

export const categories = [
  {
    id: 323,
    name: "Industrial Automation & Motion Controls",
    thumbnail_url: "/bosch 3.webp",
    count: 5,
    slug: "",
  },
  {
    id: 432,
    name: "Home & Garden",
    thumbnail_url: "/cl2.webp",
    count: 5,
    slug: "",
  },
  {
    id: 234,
    name: "Consumer Electronics",
    thumbnail_url: "/fs1.webp",
    count: 4,
    slug: "",
  },
];
